### PR TITLE
Network ringbuffer

### PR DESCRIPTION
**Pull request by jpfr**
Up for discussion, not immediate merging...

This basically enhances the connection struct to enable future implementations of ringbuffers for receiving and sending. Note the different `releaseSendBuffer` and `releaseRecvBuffer`.

```c
struct UA_Connection {
    UA_ConnectionState state;
    UA_ConnectionConfig localConf;
    UA_ConnectionConfig remoteConf;
    UA_SecureChannel *channel;
    UA_Int32 sockfd;
    void *handle;
    UA_ByteString incompleteMessage;
    UA_StatusCode (*getSendBuffer)(UA_Connection *connection, UA_ByteString *buf);
    void (*releaseSendBuffer)(UA_Connection *connection, UA_ByteString *buf);
    UA_StatusCode (*send)(UA_Connection *connection, UA_ByteString *buf, size_t buflen);
    UA_StatusCode (*recv)(UA_Connection *connection, UA_ByteString *response, UA_UInt32 timeout);
    void (*releaseRecvBuffer)(UA_Connection *connection, UA_ByteString *buf);
    void (*close)(UA_Connection *connection);
};
```

Buffer handling is a bit more complicated (but not much) when half-received messages are copied onto the heap.

### CODE REVIEW

**Comment by Stasik0** [comment]
does it break the compatibility with old alternative networklayers?

**Comment by jpfr** [comment]
Yes. I will fix the experimental UDP layer.
Anything else?

**Comment by Stasik0** [comment]
@LEvertz does it affect our network layer?
@jpfr what is the performance-surplus?

**Comment by Stasik0** [comment]
@jpfr I think, it is clear to go, no one just wants to resolve conflicts ;)

**Comment by Stasik0** [comment]
since the interface of connection changed a bit, it may be a problem for @LEvertz, but he did not say anything for 3 weeks ;)

**Pull request merged**
