### PR TITLE
adding clang to travis builds

### PR DESCRIPTION
**Pull request by HolgerJeromin**
clang has nice error messages

### CODE REVIEW

**Comment by Stasik0** [comment]
but its broken. with somehting like ck_assert_ptr_eq, @ngoossens didn't you modified these lines recently? Weren't you using clang aswell? compare https://travis-ci.org/acplt/open62541/jobs/78379731#L2231

**Comment by ngoossens** [comment]
It might be because of version differences in the check library. I am using 0.10.0 but the Travis CI config is using 0.9.10. It seems they made some fixes to this function in 0.9.12: http://check.sourceforge.net/NEWS.

**Comment by HolgerJeromin** [comment]
Perhaps some (NOT APPLE) things are better (!CLANG) but i am not sure. 
Thats why i made this PR. :-)

**Comment by Stasik0** [comment]
@ngoossens unfortunately i cannot find any newer check version for ubuntu http://security.ubuntu.com/ubuntu/pool/main/c/check/

**Comment by HolgerJeromin** [comment]
you are probably right http://sourceforge.net/p/check/bugs/91/ seems like our problem.

**Comment by HolgerJeromin** [comment]
debian-next has it. Perhaps this is working: https://packages.debian.org/stretch/check

**Comment by Stasik0** [comment]
okay, it compiles now with cmake 0.10.0 but crashes on start with a segfault.. wtf? is it a clang problem? https://travis-ci.org/acplt/open62541/jobs/78385600#L2294

**Comment by ngoossens** [comment]
Hmm, `/server` runs without issue here and I can browse it too. Again my system is a few versions ahead though:
```
clang --version
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```
vs Travis CI:
```
clang --version
clang version 3.4 (tags/RELEASE_34/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
```

**Comment by Stasik0** [comment]
it is darvin, not linux -> proposal can we disable valgrind and gcov for clang?

**Comment by ngoossens** [comment]
Travis supports OS X (http://docs.travis-ci.com/user/multi-os/) and we can use the $TRAVIS_OS_NAME variable to split the build scripts e.g. https://github.com/numenta/nupic/blob/master/.travis.yml

Doing that is a much bigger change though.

**Comment by HolgerJeromin** [comment]
we should disable valgrind only if we are sure this segfault is a false alarm.

**Comment by Stasik0** [comment]
yea, i can test on 32 bit linux

**Pull request merged**
