### PR TITLE
Unsigned array size

### PR DESCRIPTION
**Pull request by jpfr**
- Make all arrays have a size_t size (a sentinel pointer value indicates if the array has length -1 "is null" on the wire)
- Get rid of calcSizeBinary a second time. This works without breaking features by letting decoded extensionobjects contain a "real" value
- Use jumptables to speed up type handling

In conclusion: less bug-prone, faster in benchmarks, less code, smaller binary

### CODE REVIEW

**Comment by jpfr** [comment]
This is ready for merging from my point of view.
But I'd prefer to have it signed off by one of the core devs.

**Comment by FlorianPalm** [comment]
I have built a the server application and run into the following errors:
- read service fails with "BadEncodingLimitsExceeded"
- the example method ping fails with "BadInternalError"
- Segmentation fault after reading the current time node (Root/Objekte/current time):
```
==14752== Invalid read of size 4
==14752==    at 0x403CCC4: UInt64_encodeBinary (ua_types_encoding_binary.c:198)
==14752==    by 0x403D15F: UA_encodeBinary (ua_types_encoding_binary.c:1095)
==14752==    by 0x403F120: Variant_encodeBinary (ua_types_encoding_binary.c:854)
==14752==    by 0x403F4F3: DataValue_encodeBinary (ua_types_encoding_binary.c:948)
==14752==    by 0x403D15F: UA_encodeBinary (ua_types_encoding_binary.c:1095)
==14752==    by 0x403D07F: Array_encodeBinary (ua_types_encoding_binary.c:364)
==14752==    by 0x403D1D5: UA_encodeBinary (ua_types_encoding_binary.c:1101)
==14752==    by 0x403FE4C: UA_SecureChannel_sendBinaryMessage (ua_securechannel.c:138)
==14752==    by 0x403AD91: invoke_service (ua_server_binary.c:183)
==14752==    by 0x4046F3E: processMSG (ua_server_binary.c:331)
==14752==    by 0x404762B: UA_Server_processBinaryMessage (ua_server_binary.c:452)
==14752==    by 0x404854F: processJobs (ua_server_worker.c:60)
==14752==  Address 0x447f970 is 0 bytes after a block of size 8 alloc'd
==14752==    at 0x402D109: calloc (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==14752==    by 0x403B92E: UA_new (ua_types.c:591)
==14752==    by 0x804AC99: readTimeData (ua_types_generated.h:125)
==14752==    by 0x404AD61: Service_Read_single (ua_services_attribute.c:131)
==14752==    by 0x404AE99: Service_Read (ua_services_attribute.c:373)
==14752==    by 0x403AD81: invoke_service (ua_server_binary.c:178)
==14752==    by 0x4046F3E: processMSG (ua_server_binary.c:331)
==14752==    by 0x404762B: UA_Server_processBinaryMessage (ua_server_binary.c:452)
==14752==    by 0x404854F: processJobs (ua_server_worker.c:60)
==14752==    by 0x4048A4B: UA_Server_run_mainloop (ua_server_worker.c:617)
==14752==    by 0x4048C39: UA_Server_run (ua_server_worker.c:660)
==14752==    by 0x804A807: main (server.c:428)
```

**Comment by Stasik0** [comment]
@FlorianPalm is your issue fixed?

**Comment by FlorianPalm** [comment]
The segmentation fault is gone. The other errors are still present.

**Comment by Stasik0** [comment]
i confirm
* cannot execute ping method
* i got a segfault reading ping's child elements

**Comment by jpfr** [comment]
Got it.
Now, open62541 lives but UA Expert crashes. :-)

**Comment by Stasik0** [comment]
I fixed the crash problem - still no review done though ;)

**Pull request merged**
