### PR TITLE
replace sprintf with its safer version because of known buffer size

### PR DESCRIPTION
**Pull request by reza-ebrahimi**
replace sprintf with its safer version because of known buffer size, I have replaced snprintf with another version vsnprintf.

### CODE REVIEW

**Comment by reza-ebrahimi** [comment]
@Stasik0 Why appveyor building process canceled?

**Comment by Stasik0** [comment]
No idea, i did not changed a bit

**Comment by reza-ebrahimi** [comment]
What's the problem do you think?

**Comment by Stasik0** [comment]
@reza-ebrahimi it was an itnernal builder error, after rebuild it worked out.. could you squash now?

**Comment by reza-ebrahimi** [comment]
@Stasik0 I can't access the code right now, I'll squash commits after 4 hours, sorry.

**Comment by Stasik0** [comment]
Np - its sunday!

**Pull request closed without merging**
