### PR TITLE
Service call implementation

### PR DESCRIPTION
**Pull request by jpfr**

### CODE REVIEW

**Comment by Stasik0** [comment]
how do i squash it properly?

**Comment by jpfr** [comment]
git checkout master
git merge --squash service_call_implementation
git commit --amend --author "ichrispa <Chris_Paul.Iatrou@tu-dresden.de>"

**Comment by Stasik0** [comment]
pulled and squashed, credits go to ichrispa, can i also remove the second branch "service_call_interface?"

**Comment by jpfr** [comment]
yes. it can be removed.

**Pull request closed without merging**
