### PR TITLE
remove multiple calls to WSAGetLastError

### PR DESCRIPTION
**Pull request by reza-ebrahimi**
remove multiple calls to WSAGetLastError()

### CODE REVIEW

**Comment by HolgerJeromin** [comment]
could you please fix the indention? (see "files changed" tab here). 
The whole code is quite chaos compared to indention, sorry for that.

**Comment by reza-ebrahimi** [comment]
@HolgerJeromin You are right, I'm going to fix it.

**Comment by HolgerJeromin** [comment]
The first occurrence of `const int last_error` has tabs and the line below has spaces.

**Comment by Stasik0** [comment]
looks good, yould you sqush the three commits into one, please?

**Comment by reza-ebrahimi** [comment]
@Stasik0 Yes, sure.

**Pull request closed without merging**
