### PR TITLE
check the resultsize before allocating results

### PR DESCRIPTION
**Pull request by jgilje**
I'm running my application with address sanitizer, and got a crash after connecting UA Expert 1.4 to my application. It's caused by the resultsSize field in UA_PublishRequest being negative (-1).

From sanitizer:
`==9736==WARNING: AddressSanitizer failed to allocate 0xfffffffffffffffc bytes`

### CODE REVIEW

**Comment by jgilje** [comment]
I'd just like to add that the AppVeyor build fail is caused network errors when fetching the dependencies (lxml => zlib)

**Comment by Stasik0** [comment]
@jgilje could you please check if you can reproduce the error with the unsigned_array branch

**Comment by jgilje** [comment]
@Stasik0 no problem, I'll test with that branch. I'm having an extended weekend now, so I won't be able to test before monday.

**Comment by jgilje** [comment]
@Stasik0 I've tested with the unsigned_array branch, no problems there. What's the plan for merging these branches?

**Comment by Stasik0** [comment]
@jgilje we kinda offered the testing of these branch in our mailing list, will probably be merged in within a week or so

**Comment by jgilje** [comment]
Ok, no worries :) I'll just close this pull request then, as the issue will be resolved when the branches merge.

**Pull request closed without merging**
