### PR TITLE
support cygwin envirnment

### LINKED ISSUE #297: cygwin compile supporting label:easy hacks
The project could compile on the cygwin environment with following changes.

```
# compiler flags
if(CMAKE_COMPILER_IS_GNUCC OR "x${CMAKE_C_COMPILER_ID}" STREQUAL "xClang")
    if(CYGWIN)
      add_definitions(-std=c99 -pipe -Wall -Wextra -Wformat -Wno-unused-parameter
                      -Wno-unused-function -Wno-unused-label -Wpointer-arith -Wreturn-type -Wsign-compare -Wmultichar
                      -Wcast-qual -Wmissing-prototypes -Wstrict-prototypes # -Wshadow -Wconversion
                      -Winit-self -Wuninitialized -Wformat-security -Wformat-nonliteral)
    endif()
    if(NOT CYGWIN)
      add_definitions(-std=c99 -pipe -Wall -Wextra -Werror -Wformat -Wno-unused-parameter
                      -Wno-unused-function -Wno-unused-label -Wpointer-arith -Wreturn-type -Wsign-compare -Wmultichar
                      -Wcast-qual -Wmissing-prototypes -Wstrict-prototypes # -Wshadow -Wconversion
                      -Winit-self -Wuninitialized -Wformat-security -Wformat-nonliteral)
    endif()
    # binary size reduction settings
	add_definitions(-ffunction-sections -fdata-sections -fno-stack-protector -fno-unwind-tables
                    -fno-asynchronous-unwind-tables -fno-math-errno -fmerge-all-constants -fno-ident)
    set(CMAKE_C_LINK_FLAGS "${CMAKE_C_LINK_FLAGS} -Wl,--gc-sections")
    set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -Wl,--gc-sections")
    set(CMAKE_SHARED_LIBRARY_LINK_C_FLAGS "") # cmake sets -rdynamic by default
	if(NOT WIN32)
     if(NOT CYGWIN)
	    add_definitions(-fvisibility=hidden -fPIC)
        set(CMAKE_C_LINK_FLAGS "${CMAKE_C_LINK_FLAGS} -Wl,-z,norelro -Wl,--hash-style=gnu -Wl,--build-id=none")
      endif()
	endif()
    if(CMAKE_BUILD_TYPE STREQUAL "MinSizeRel" OR CMAKE_BUILD_TYPE STREQUAL "Release")
        set(CMAKE_C_LINK_FLAGS "${CMAKE_C_LINK_FLAGS} -s")
        set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -s")
    endif()
endif()
```

### PR DESCRIPTION
**Pull request by joyhope**
It could be compiled in the cygwin environment.
closes #297

### CODE REVIEW

**Comment by Stasik0** [comment]
@joyhope so, you disabled -Werror? What was the reason? Does the compiler not support it, or are there some warnings? Its probably better to fix the warnings?

**Comment by joyhope** [comment]
My result

###
lee@lee-Thinkpad /cygdrive/e/gitprj/open62541/build
$ cmake -DBUILD_EXAMPLESERVER=ON -DBUILD_EXAMPLECLIENT=ON ..
-- Git version: v0.1.0-RC4-352-g11fd400-dirty
-- Configuring done
-- Generating done
-- Build files have been written to: /cygdrive/e/gitprj/open62541/build

lee@lee-Thinkpad /cygdrive/e/gitprj/open62541/build
$ make
Scanning dependencies of target open62541-object
[  3%] Building C object CMakeFiles/open62541-object.dir/src/ua_types.c.o
/cygdrive/e/gitprj/open62541/src/ua_types.c: 在函数‘UA_Guid_random’中:
/cygdrive/e/gitprj/open62541/src/ua_types.c:246:5: 错误：隐式声明函数‘rand_r’
[-Werror=implicit-function-declaration]
     result.data1 = RAND(seed);
     ^
cc1: all warnings being treated as errors
CMakeFiles/open62541-object.dir/build.make:77: recipe for target
'CMakeFiles/ope
n62541-object.dir/src/ua_types.c.o' failed
make[2]: *** [CMakeFiles/open62541-object.dir/src/ua_types.c.o] Error 1
CMakeFiles/Makefile2:165: recipe for target
'CMakeFiles/open62541-object.dir/all
' failed
make[1]: *** [CMakeFiles/open62541-object.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2
###

Read the code, I did not find the problem. It may be macro expanded. The
rand_r function is missing in the head file.

I try to find the answer.

**Comment by joyhope** [comment]
in the cygwin  stdlib.h

#ifdef __USE_POSIX
/* Reentrant interface according to POSIX.1.  */
extern int rand_r (unsigned int *__seed) __THROW;
#endif


The rand_r declaration is  under __USE_POSIX .

The project is using  c99 .   I guess the problem comes from this.

I did not find the problem way to solve the problem, so I removed Werror.

It may caused by cygwin head file define.

**Comment by joyhope** [comment]
The Werror will cause another error in the cygwin environment

###
[ 96%] Building C object CMakeFiles/server.dir/examples/server.c.o
/cygdrive/e/gitprj/open62541/examples/server.c:27:0: 错误：“__USE_XOPEN2K”重定
义 [-Werror]
 #define __USE_XOPEN2K
 ^
In file included from /usr/include/_ansi.h:16:0,
                 from /usr/include/time.h:10,
                 from /cygdrive/e/gitprj/open62541/examples/server.c:7:
/usr/include/sys/config.h:236:0: 附注：这是先前定义的位置
 #define __USE_XOPEN2K 1
 ^
cc1: all warnings being treated as errors
CMakeFiles/server.dir/build.make:54: recipe for target
'CMakeFiles/server.dir/ex
amples/server.c.o' failed
make[2]: *** [CMakeFiles/server.dir/examples/server.c.o] Error 1
CMakeFiles/Makefile2:200: recipe for target 'CMakeFiles/server.dir/all'
failed
make[1]: *** [CMakeFiles/server.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2
###

I may find other clean solution.

**Comment by Stasik0** [comment]
@joyhope okay, now they seem to be equal?
    if(CYGWIN)
      add_definitions(-std=c99 -pipe -Wall -Wextra -Werror -Wformat -Wno-unused-parameter
                      -Wno-unused-function -Wno-unused-label -Wpointer-arith -Wreturn-type -Wsign-compare -Wmultichar
                      -Wcast-qual -Wmissing-prototypes -Wstrict-prototypes # -Wshadow -Wconversion
                      -Winit-self -Wuninitialized -Wformat-security -Wformat-nonliteral)
    endif()
    if(NOT CYGWIN)
      add_definitions(-std=c99 -pipe -Wall -Wextra -Werror -Wformat -Wno-unused-parameter
                      -Wno-unused-function -Wno-unused-label -Wpointer-arith -Wreturn-type -Wsign-compare -Wmultichar
                      -Wcast-qual -Wmissing-prototypes -Wstrict-prototypes # -Wshadow -Wconversion
                      -Winit-self -Wuninitialized -Wformat-security -Wformat-nonliteral)
    endif()

so now we do not need the two cases anylonger?

**Comment by joyhope** [comment]
You are right.  I forget to back.

I changed again.

**Comment by joyhope** [comment]
I pushed the latest changes to my repository with the Werror supporting.

I did not know why I could not pull the new request for the changes.

**Comment by Stasik0** [comment]
@joyhope perfect, could you squash your commits to one, please? https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

**Comment by joyhope** [comment]
I made it.

**Comment by HolgerJeromin** [comment]
Your editor killed some white spaces at the end of some lines. This is probably not bad, but touches the statistics for commits.

**Comment by joyhope** [comment]
I use atom, I also notice this problem, but I did not know how to solve it.

**Pull request merged**
