### PR TITLE
using ${PYTHON_EXECUTABLE} and a better check for lxml.

### LINKED ISSUE #263: check python install
open62541 needs a python and python-lxml install (always?) so it would be nicer to check the availability somewhere. Otherwise you get a ugly abort from make.
This is especially important for windows...

### PR DESCRIPTION
**Pull request by HolgerJeromin**
this could fix #263 with python 3 and python 2.x

### CODE REVIEW

**Comment by Stasik0** [comment]
linux builds are failing

https://travis-ci.org/acplt/open62541/builds/66177702#L460

eventually Python-lxml vs python-lxml ?

**Comment by Stasik0** [comment]
@HolgerJeromin it may be a py2 and py3 problem, you have py3, the build server py2.7. ${ PYTHON_VERSION} is there

**Comment by HolgerJeromin** [comment]
Stasik calm down. I did it with a PR to check travis 2.3 python. (and checked my linux box at home with 2.7) :-)

**Comment by Stasik0** [comment]
@HolgerJeromin can't calm down, too much coffee!

**Pull request merged**
