### PR TITLE
Fix Visual Studio build

### PR DESCRIPTION
**Pull request by stephanhensel**
Pull request as discussed in #256

### CODE REVIEW

**Comment by Stasik0** [comment]
@stephanhensel: did it work for MSVS? as you see the build breaks for GCC. I cannot edit your PR easily, could you please add this to your repository? 
```
#ifdef _MSC_VER
    #include <io.h> //access
#else
    #include <unistd.h> //access
#endif
```
Then I will merge it in.

**Comment by Stasik0** [comment]
@stephanhensel 
I would also advice you to edit ua_config.h.in by adding
```
#if defined(_MSC_VER) && _MSC_VER >= 1400
#   define UA_RESTRICT __restrict
#else
#   define UA_RESTRICT restrict
#endif
```

and use `US_RESTRICT` consistently

**Comment by jpfr** [comment]
Thanks for the pull!

@Stasik0 What about putting it into `src/ua_util.h`?
`ua_config.h.in` contains the macros that are set by cmake.

@stephanhensel 
Do you need to replace unistd.h, a standard POSIX library, by the windows-specific io.h?

**Comment by Stasik0** [comment]
Yea, np.

The access function is actually not relevant for windows, so we could also comment it out completely

**Comment by stephanhensel** [comment]
I changed the ua_config.h.in as Stasik0 told. This works for Visual Studio. Can you now merge it in?

**Comment by Stasik0** [comment]
it still break, i will merge it on my own, wait a second

**Pull request closed without merging**
