### PR TITLE
Aligning the server with the Highlevel API

### PR DESCRIPTION
**Pull request by jpfr**
Due to popular request (@ichrispa), this branch proposes a similar API for the server and client.

1. Aligned between client and server are
   - Node and references creation + deletion
   - Attribute reading and writing
2. The client highlevel API sits "on top" of the raw services and is branched out into separate files
3. Bugfix: Objects are now properly destroyed if their ObjectType has a destructor

@ichrispa Maybe we can have a 30min call to review the changes.

### CODE REVIEW

**Comment by HolgerJeromin** [comment]
Do we have or want the high level api behind an ifdef? 
This question blocks #430

**Comment by jpfr** [comment]
If the goal is to just reduce the binary size, we can leave it in.
Size-conscious users will use static binaries. And every unused highlevel function has zero overhead.

**Comment by HolgerJeromin** [comment]
Ok. Good point. 
Then we could merge #430?

**Comment by ichrispa** [comment]
Very nice. I will go over the changes to both APIs ASAP (theres a lot of changes), but at first sight the functionality I need for my projects seems to have been maintained.

**Comment by jpfr** [comment]
Merged in c9ae4288d830fbcfb1bb65f526f4393b87dc45d4

**Pull request closed without merging**
