### PR TITLE
remove multiple calls to WSAGetLastError()

### PR DESCRIPTION
**Pull request by reza-ebrahimi**
remove multiple calls to WSAGetLastError()

### CODE REVIEW

**Comment by reza-ebrahimi** [comment]
@Stasik0 Is it ok?

**Comment by Stasik0** [comment]
well, not really, since you have all the random stuff now also included in it https://github.com/acplt/open62541/pull/411/files... probably you squashed one commit too much.... hmm what should we do?

**Comment by reza-ebrahimi** [comment]
@Stasik0 I think the solution is remove my master repository and fork it again, then apply my changes and commit.

**Comment by HolgerJeromin** [comment]
perhaps it is easier to bring the old #409 in shape :-)

**Pull request closed without merging**
